// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Squares_server.Data;

namespace Squares_server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Squares_server.Models.NamedList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NamedLists");
                });

            modelBuilder.Entity("Squares_server.Models.NamedListPoint", b =>
                {
                    b.Property<int>("NamedListId")
                        .HasColumnType("int");

                    b.Property<int>("PointModelId")
                        .HasColumnType("int");

                    b.HasKey("NamedListId", "PointModelId");

                    b.HasIndex("PointModelId");

                    b.ToTable("NamedListPoints");
                });

            modelBuilder.Entity("Squares_server.Models.PointModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("xCoord")
                        .HasColumnType("int");

                    b.Property<int>("yCoord")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("Squares_server.Models.NamedListPoint", b =>
                {
                    b.HasOne("Squares_server.Models.NamedList", "NamedList")
                        .WithMany("NamedListPoints")
                        .HasForeignKey("NamedListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Squares_server.Models.PointModel", "PointModel")
                        .WithMany("NamedListPoints")
                        .HasForeignKey("PointModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NamedList");

                    b.Navigation("PointModel");
                });

            modelBuilder.Entity("Squares_server.Models.NamedList", b =>
                {
                    b.Navigation("NamedListPoints");
                });

            modelBuilder.Entity("Squares_server.Models.PointModel", b =>
                {
                    b.Navigation("NamedListPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
